### ISSUE TITLE
Move weapon/projectile related fields to weapon

### ISSUE THREAD

**Issue by JeremyPlott** [CoreyMeyerCin/TopDungeon#77]
projectile + weapon related fields like:
lifespan
projectilespeed
firedelay

etc should be fields that are on the weapon/projectile itself rather than on the player/enemy

And decouple it so that there is a projectile.cs class that controls the projectile it creates

**Comment by CoreyMeyerCin** [comment]
Finished, there are several attack related fields that I did not move: attackSpeed, lifeSteal etc, because if we upgrade this on our player they need to be transferred to all weapons that we pick up not just the one that we currently have equipped. Thoughts? Does it look good to you? I will leave this open for now and feel free to comment or close it if you are comfortable with it.

**Comment by CoreyMeyerCin** [comment]
@JeremyPlott

**Comment by JeremyPlott** [comment]
@CoreyMeyerCin mb didn't see ping notif anywhere. Yes, attack speed and lifesteal and stats like that should stay in fighter.stats. I didn't thoroughly look at everything but it looks more sensibly organized now 👍
